// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD24nLKLASxsOIV5D-txUouGkW3M1p44jA',
    appId: '1:819202745084:web:ef82d75dfaccffdf10ad79',
    messagingSenderId: '819202745084',
    projectId: 'interactopia-74b7a',
    authDomain: 'interactopia-74b7a.firebaseapp.com',
    storageBucket: 'interactopia-74b7a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxEHIojb_6BchRJNsOMLN5OI83Z5E7Kgo',
    appId: '1:819202745084:android:4d5e8110985fee9a10ad79',
    messagingSenderId: '819202745084',
    projectId: 'interactopia-74b7a',
    storageBucket: 'interactopia-74b7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxrAKyE9R8y-35a2ArdODy9T8wTUlNTBI',
    appId: '1:819202745084:ios:344e432f4ee5230a10ad79',
    messagingSenderId: '819202745084',
    projectId: 'interactopia-74b7a',
    storageBucket: 'interactopia-74b7a.appspot.com',
    iosBundleId: 'com.example.interactopia',
  );
}
